version: '3.8'

services:
  backend:
    build: backend/
    container_name: nest_chat_gpt
    ports:
      - "3000:3000"

    command: npm run start:dev
  frontend:
    image: node:18
    container_name: vue_chat_gpt
    working_dir: /app
    volumes:
      - ./web-client:/app
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://backend:3000
    command: sh -c "npm install && npm run serve -- --host=0.0.0.0"
volumes:
  mongo_data: